Account
wanted-pre-onboarding-8team/week1-1-wanted-pre-onboarding pull request #2
Opened 2022-12-21 11:23 UTC by dev-dong-su

# Assignment #1 ~ #3 번과 관련된 기능 입니다.
```
├── apis
├── components
│   ├── account
│   ├── common
│   └── todo
├── contexts
├── hooks
├── pages
├── router
└── utils

```
<br></br>

# hooks

### useAuthMethod
> 사용자가 login을 클릭하거나 join을 클릭시 변하는 상태를 합니다.
### useInput
> 패턴이 있다면 valid한지 안한지, value의 변화 등, Input의 상태를 관리합니다.
```javascript
const email = useInput({
      initialValue: '',
      errorMessage: '이메일 형식이 올바르지 않습니다.', // valid 하지 않다면 출력할 메시지
      pattern: 'email', // 사용할 패턴
      required: true,
    }),
```
### useLocalStorage
> LocalStorage를 관리합니다. storedValue로 조회하고 setValue, deleteValue 로 삽입 삭제합니다.
### useRequest
> API통신을 관리합니다. submitFunction(요청시 사용할 메소드), formData를 받아서 에러를 핸들링 합니다. 사용측은 .then으로 이후의 작업을 정의합니다.
```javascript
    handleRequest({
      submitFunction: join,
      formData: { email: form.email.value, password: form.password.value },
    }).then(response => {
      alert('회원가입 성공!');
      navigate('/');
    });
```
<br></br>

# components
```
├── components
│   ├── account
│   ├── common
│   └── todo
```
## common
> 원자성을 가지는 컴포넌트를 넣어두었습니다.
```
Button.js
Container.js    # 컴포넌트의 layout을 잡기위한 컴포넌트 입니다.
Input.js
PageTemplate.js # 페이지의 layout을 잡기위한 컴포넌트 입니다.
Container.js
Radio.js        # Account 페이지 에서 login과 join을 선택하기 위한 Radio
```
## account
> Account 페이지에서 사용하는 컴포넌트 입니다. login과 join을 선택하여 렌더링 합니다.
## login
> 로그인 컴포넌트 입니다. 
> useInput으로 이메일과 비밀번호의 상태를 관리하고 두개의 Input이 valid하면 button을 활성화 시키고 useLocalStorage의 setValue로 LocalStorage에 저장합니다.
```javascript
  const handleOnSubmit = event => {
    event.preventDefault();
    handleRequest({
      submitFunction: login,
      formData: { email: form.email.value, password: form.password.value },
    }).then(response => {
      setValue(response.data['access_token']);
      navigate('/todo');
    });
  };
```
## join
> 회원가입 컴포넌트 입니다. 마찬가지로 useInput으로 Input을 관리합니다.

<br></br>
# Util

## Validations
> pattern을 인자로 받아 patterns에서 해당하는 정규식 or 패턴을 반환 합니다.
```javascript
const Validations = (pattern) => {
  const patterns = {
    email: '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$',
    password: '^(?=.*[a-zA-Z])(?=.*).{8,25}$',
  };

  return patterns[pattern];
};
```

<br></br>
# Router
> PrivateRouter에서 useLocalStorage를 사용해서 LocalStorage에
> access_token이 있는지 검사하고 없다면 AccountPage로 있다면 ToDo로  
```javascript
export const PrivateRouter = () => {
  const { storedValue } = useLocalStorage('access_token');

  return storedValue === undefined || storedValue === null ? <Navigate to="/" /> : <ToDoPage />;
};

export const router = createBrowserRouter([
  {
    path: '/',
    element: <AccountPage />,
  },
  {
    path: '/todo',
    element: <PrivateRouter />,
  },
]);
```

## App.js 에서 사용합니다.

```javascript
function App() {
  return <RouterProvider router={router} />;
}
```

2022-12-21 13:02 UTC, leezer94 reviewed
추가적으로
이미 존재하는 회원의 경우에 가입을 하면 400 에러 이후에 동일한 회원정보가 있다는 alert와 회원가입이 성공되었다는 alert 두개가 다 뜨는것 같아서 확인 부탁드립니다!

useAuthMethod hook 부분이 궁금해서 역할도 간단하게 설명해주실수 있으면 감사하겠습니다!

제가 놓친 부분일지는 모르겠는데 상태 코드 별 에러핸들링이 되어있으면 더 좋을것 같습니다

마지막으로 import시에 절대경로를 쓰면 폴더구조 변경이나 디렉토리 이동시에도 핸들링이 더 쉬울것 같습니다!

고생하셨습니다.

2022-12-21 13:02 UTC, leezer94 commented on postcss.config.js
> +};
옮겨지면서 마지막 줄 개행이 안된것 같아요 EOL 확인 부탁드립니다~

2022-12-21 13:02 UTC, leezer94 commented on src/apis/index.js
> +  baseURL: 'https://pre-onboarding-selection-task.shop/',
baseURL 도 .env에서 관리되면 좋을것 같습니다.

2022-12-21 13:02 UTC, leezer94 commented on src/components/account/Join.js
> +      <Input type="password" label="Password" {...form.password} />
minLength 를 추가해주면 1차적인 검증이 가능해 더 좋을것 같습니다

2022-12-21 13:02 UTC, leezer94 commented on src/utils/Validations.js
> +    password: '^(?=.*[a-zA-Z])(?=.*).{8,25}$',
틀리기 쉬운 정규식 같은 경우에는 상수화 하는것이 좋다고 생각하는데 어떠신가요 ?

2022-12-21 15:10 UTC, dev-dong-su commented on postcss.config.js
> +};
확인후 수정하였습니다~

2022-12-21 15:11 UTC, dev-dong-su commented on src/utils/Validations.js
> +    password: '^(?=.*[a-zA-Z])(?=.*).{8,25}$',
짜면서 놓친 부분인것 같은데 감사합니다~ 바로 수정하였습니다!

2022-12-21 15:25 UTC, dev-dong-su commented on src/components/account/Join.js
> +      <Input type="password" label="Password" {...form.password} />
놓친 부분들을 잘 봐주셔서 감사합니다!

> 이미 존재하는 회원의 경우에 가입을 하면 400 에러 이후에 동일한 회원정보가 있다는 alert와 회원가입이 성공되었다는 alert 두개가 다 뜨는것 같아서 확인 부탁드립니다!

이 문제에 경우 제 useRequest 와 component 사이에 logic의 설계가 잘못된걸 확인후 모든 응답의 처리를 useRequest가 할 수 있게 바꾸었고 에러 핸들링 부분에 상태 코드 별 핸들링을 추가했습니다.

Validations 도 상수 처리 했고 ErrorMessage는 leezer94님 코드 참고해서 넣어봤습니다! 아직 수정하지 못한 사항은 자고 일어나서 진행해 보겠습니다~!

2022-12-21 19:53 UTC, minkyung00 requested changes
최대한 꼼꼼하게 남겨보려고 했더니 리뷰가 너무 많아진건 아닌지 .. 마음에 걸리네요 😅

제가 제시한 의견이 옳다는 것은 아니고 단지 이런 방법은 어떨까 제안을 드린 것이니 오해 없으시길 바랍니다! (별로면 솔직하게 말해주세요! )
그리고 질문은 정말 궁금해서 물어본 것이니까 이 부분도 오해 없으셨으면 좋겠습니다!

부족하거나 궁금하신 사항이 생긴다면 언제든 말해주세요!

2022-12-21 19:53 UTC, newminkyung commented on public/index.html
> +<html lang="en">
사소한거지만 우리 사이트에서는 한국어를 사용하니까`lang="ko-KR"`으로 설정해서 접근성도 같이 고려하면 좋을 것 같습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/apis/auth.js
> +export const join = formData => client.post('/auth/signup', { email: formData.email, password: formData.password });
요청 url에 맞게 signup으로 통일하는 것은 어떻게 생각하시나요? signup, join 모두 동일한 의미이지만 통일성 있게 하나로 선택하는 것이 좋을 것 같습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/apis/auth.js
> +export const login = formData => client.post('/auth/signin', { email: formData.email, password: formData.password });
유지보수를 위해 **api를 사용하는 곳**에서 payload를 넘겨주는 것이 어떨까요?

사용하는 곳에서 어떤 데이터가 전송되는지 아는 것이 더 명시적일 것 같습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/utils/constants/Validations.js
> +const Validations = {
상수니까 전부 대문자로 쓰는게 좋을 것 같습니다~

2022-12-21 19:53 UTC, newminkyung commented on src/router/Router.js
> +  return storedValue === undefined || storedValue === null ? <Navigate to="/" /> : <TmpPpage />;
[null 병합 연산자](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)를 쓰면 더 깔끔하게 작성할 수 있습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/pages/TMP.js
> +const TmpPpage = () => {
hoxy 오타인가요?

2022-12-21 19:53 UTC, newminkyung commented on src/pages/TMP.js
> +    <PageTemplate>
이 TmpPpage 없이 <PageTemplate>를 사용하는건 어떨까요? TmpPpage에서는 별다른 로직이 없고 <PageTemplate>만 반환하고 있습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/router/Router.js
> +    element: <PrivateRouter />,
위 코드만 봤을 때는 access 토큰이 있으면 TmpPpage가 반환되는데 todo 페이지가 제대로 렌더링이 되는지 궁금합니다!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useLocalStorage.js
> +    if (typeof window === 'undefined') {
혹시 이 코드는 어떨 때를 고려해서 작성하신건가요? window 객체가 undefined인 경우도 있나요? 몰라서 물어봅니다 ..

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useLocalStorage.js
> +    try {
이 파일에서 try catch는 불필요해보이는데 혹시 의도가 있나요?

2022-12-21 19:53 UTC, newminkyung commented on src/components/RadioGroup.js
> +      <RadioContext.Provider value={rest}>{children}</RadioContext.Provider>
여기서 context를 사용한 이유가 있을까요? 

저는 주로 context는 하위 컴포넌트가 모두 렌더링 + 복잡한 트리구조 때문에 로그인 유무나 테마같이 전역으로 관리해야하는 값이 아니면 잘 사용하지 않아서요!

로그인 / 회원가입 상태를 부모 컴포넌트에서 props로 전달해도 drilling이 심하지 않을 것 같은데 의견이 궁금합니다!

2022-12-21 19:53 UTC, newminkyung commented on src/components/common/Input.js
> +const Container = tw.div`relative w-full`;
어떤 컴포넌트 앞에 Styled가 있고 어떤 컴포넌트는 없는데 둘의 차이가 무엇인가요? styled-component를 아직 안써봐서 잘 모르겠네요😅

2022-12-21 19:53 UTC, newminkyung commented on src/components/common/Container.js
> +const ContainerStyle = tw.div`flex flex-col shadow-md items-center w-11/12 h-5/6 mx-auto rounded-xl gap-2 bg-slate-50 my-auto`;
StyledContainer로 수정하는게 더 일관성 있을 것 같습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/components/common/Radio.js
> +function Radio({ children, value, name, defaultChecked, disabled }) {
`defaultChecked` 이 props는 사용되고 있지 않습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useAuthMethod.js
> +    onChange: setAuthMethod,
onChange 이벤트와 헷갈릴 수 있을 것 같습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useAuthMethod.js
> +  const [authMethod, setAuthMethod] = useState(initialValue);
authMethod라고 하면 인증 관련 함수를 의미하는 것 같아서 오해할 수 있을 것 같습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useAuthMethod.js
> +const useAuthMethod = initialValue => {
hook으로 따로 분리한 이유가 있을까요? 바로 Account에서 setState로 관리해도 좋을 것 같은데 의도가 있는지 궁금합니다!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useInput.js
> +    event.target.value.match(getPattern) ? setValid(pre => true) : setValid(pre => false);
`!!` 연산자를 이용해서 더 깔끔하게 작성할 수 있을 것 같습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useInput.js
> +  const getPattern = Validations[pattern];
동사로 시작해서 함수로 오해할 수 있을 것 같습니다! 정규식을 의미하는 변수이므로 regexp라는 변수명 제안해봅니다 ㅎㅎ

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useInput.js
> +import { useMemo, useState } from 'react';
`useMemo` 는 사용하고 있지 않네요!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useRequest.js
> +  const handleRequest = ({submitFunction, formData, action}) =>
`async await`를 사용해보는건 어떨까요? `try catch`로 성공과 실패 코드를 나눠서 읽을 수 있어 체이닝보다 가독성이 좋습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useRequest.js
> +      if (error.response.status === 400) {
객체 구조 분해 할당을 사용하면 코드가 더 깔끔할 것 같습니다!

2022-12-21 19:53 UTC, newminkyung commented on src/hooks/useRequest.js
> +  const loginRequest = (response) => {
loginRequest라는 이름을 보고 로그인 성공 후 실행되는 로직들이라는 것을 알기 어려운 것 같습니다! 

`handleLoginSuccess`라는 이름은 어떠신지 의견 궁금합니다!

2022-12-21 19:53 UTC, minkyung00 commented on src/hooks/useLocalStorage.js
> +  return { storedValue, setValue, deleteValue };
value라는 이름은 스토리지에 저장된 값이라는 것을 파악하기에는 포괄적인 단어인 것 같습니다!

`storageValue`로 범위를 좁혀보는건 어떨까요?

2022-12-21 19:53 UTC, minkyung00 commented on src/components/common/Radio.js
> +        type="radio"
혹시 `input type="radio"`로 구현하신 이유가 있나요?

저는 주로 옵션을 선택할 때 라디오 버튼을 사용하는데 또 다른 의미가 있나요?!

2022-12-21 19:53 UTC, minkyung00 commented on src/components/common/PageTemplate.js
> +const PageTemplate = ({ children, ...rest }) => {
`common/Container`는 컴포넌트에서 사용하는 컨테이너고 `PageTemplate`는 페이지에서 사용하는 컨테이너인가요?

PageContainer로 이름을 통일해보는 것은 어떨까요? Template와 Container가 함께 쓰여서 헷갈릴 수 있을 것 같습니다!

2022-12-21 19:53 UTC, minkyung00 commented on src/pages/AccountPage.js
> +import PageTemplate from '../components/common/PageTemplate';
account, common 폴더 index.js에 export를 모아두면 파일 경로를 조금이나마 깔끔하게 작성할 수 있을 것 같습니다 ㅎㅎ

2022-12-21 19:53 UTC, minkyung00 commented on src/components/account/Join.js
> +      pattern: 'email',
pattern이라는 키 값과 email이라는 값의 연관성이 떨어지는 것 같습니다!

input의 type을 나타내는 것이니까 `type` 이라는 키 값은 어떠신가요?!

2022-12-21 19:53 UTC, minkyung00 commented on src/components/account/Join.js
> +      errorMessage: '비밀번호가 8자 이상인지 확인해 주세요.',
이 에러 메시지도 상수로 관리하면 좋겠네요!

2022-12-21 19:53 UTC, minkyung00 commented on src/utils/constants/ErrorMessage.js
> +const MESSAGE = {
utils 폴더에는 주로 자주 사용되는 함수들이 포함되므로 상수를 관리하는 contants는 따로 폴더로 분리하는 것이 좋을 것 같습니다!

2022-12-22 05:23 UTC, Limttugi commented on src/utils/constants/Validations.js
> +    email: '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$',
유효성 검사 저희 정규식 말고 include @ 랑 length >= 8 쓰기로 했었던 것 같아요 ... :]

2022-12-22 05:23 UTC, Limttugi commented on src/components/common/Input.js
> +      {!valid && <ErrorMessage>{errorMessage}</ErrorMessage>}
Input에 아무것도 입력되지 않았을 때도 에러메시지가 나오더라구요!
제 생각에는 length !== 0처럼 조건을 하나 더 추가하던가 로직을 조금 변경하는게 좋아보여요!

2022-12-22 05:57 UTC, leezer94 commented on src/apis/index.js
> +  baseURL: 'https://pre-onboarding-selection-task.shop/',
baseURL 환경 변수 처리하였습니다. 
.env 생성하시고 
`REACT_APP_BASE_URL='https://pre-onboarding-selection-task.shop/'` 추가해주시면 될것 같습니다.

.gitignore 에도 .env 추가했습니다.

2022-12-22 07:37 UTC, dev-dong-su commented on src/apis/index.js
> +  baseURL: 'https://pre-onboarding-selection-task.shop/',
넵 확인하였습니다~ 이따가 권한 얻으시면 push 해주시면 될것 같습니다!

2022-12-22 07:42 UTC, dev-dong-su commented on public/index.html
> +<html lang="en">
수정하였습니다~!

2022-12-22 07:42 UTC, dev-dong-su commented on src/apis/auth.js
> +export const join = formData => client.post('/auth/signup', { email: formData.email, password: formData.password });
좋은 생각인것 같습니다! 수정하겠습니다~

2022-12-22 07:43 UTC, dev-dong-su commented on src/pages/TMP.js
> +const TmpPpage = () => {
수정 하였습니다~

2022-12-22 08:01 UTC, dev-dong-su commented on src/apis/auth.js
> +export const login = formData => client.post('/auth/signin', { email: formData.email, password: formData.password });
```javascript
   #사용측
    handleRequest({
        submitFunction: signUp,
        # payload -> formData
        formData: {email: form.email.value, password: form.password.value},
        action: 'JOIN',
      }
    )
```

```javascript
  # 핸들러
  const handleRequest = ({submitFunction, formData, action}) =>
    submitFunction(formData).then(response => responseAction({action, response})
    ).catch(error => {
      if (error.response.status === 400) {
        alert(MESSAGE.USER_ALREY_EXIST);
      } else if (error.response.status === 401) {
        alert(MESSAGE.USER_NOT_MATCH);
      } else if (error.response.status === 404) {
        alert(MESSAGE.USER_NOT_FOUND);
      } else if (error.request) { // 요청이 잘못된 경우
        console.log(error.request);
        setError(true);
      }
    });
```
useRequest 라는 훅에서 모든 요청을 object 형식으로 던져서 좀더 payload를 유연하게 받으려고 해본건데 사용측에서 formData를 정의하긴 합니다!

2022-12-22 08:12 UTC, dev-dong-su commented on src/router/Router.js
> +  return storedValue === undefined || storedValue === null ? <Navigate to="/" /> : <TmpPpage />;
좋은 생각인것 같아요~ 그런데 제가 병합 연산자를 써본적이 없어서 문서를 읽어봐도 storedValue에 값이 없으면 "/"로 가고 있다면 임시 페이지로 가게 어떻게 응용할지 잘 모르겠습니다! 나중에 수정해주시고 푸시 해주실 수 있을까용

2022-12-22 08:16 UTC, dev-dong-su commented on src/pages/TMP.js
> +    <PageTemplate>
TmpPage는 임시로 두었는데 나중에 TodoPage로 바꾸면 될것 같아요~

2022-12-22 08:18 UTC, dev-dong-su commented on src/router/Router.js
> +    element: <PrivateRouter />,
아직 TodoPage는 안넣어놔서 나중에 이번 PR이 머지되면 제가 Todo관련 과제 4~6번 올리면 확인 가능할겁니다!

2022-12-22 08:19 UTC, dev-dong-su commented on src/hooks/useLocalStorage.js
> +    if (typeof window === 'undefined') {
아아 서버사이드 렌더링을 할 경우에 사용하는 건데 전에 사용하던 코드를 가져왔더니 그대로 붙었네용;; 삭제하겠습니당~

2022-12-22 08:25 UTC, dev-dong-su commented on src/hooks/useLocalStorage.js
> +    try {
try catch가 의미가 없는것 같아서 삭제 하겠습니다!

2022-12-22 08:37 UTC, dev-dong-su commented on src/components/common/Input.js
> +const Container = tw.div`relative w-full`;
확인후 수정하였습니다~!

2022-12-22 08:41 UTC, dev-dong-su commented on src/components/common/PageTemplate.js
> +const PageTemplate = ({ children, ...rest }) => {
그러네용 헷갈릴 수 있을 것 같아서 common/Container 는 별로 의미없는 분류인것 같아서 제거 했고 PageContainer 로 리펙토링 하겠습니다~

2022-12-22 09:04 UTC, dev-dong-su commented on src/components/common/Container.js
> +const ContainerStyle = tw.div`flex flex-col shadow-md items-center w-11/12 h-5/6 mx-auto rounded-xl gap-2 bg-slate-50 my-auto`;
common/Container 의 분리가 의미 없다고 생각이 들어서 제거하였습니다!

2022-12-22 09:18 UTC, leezer94 commented on src/components/common/Radio.js
> +function Radio({ children, value, name, defaultChecked, disabled }) {
사용되지 않는 props 제거후 push 완료 해서 resolve 하겠습니다 ~

2022-12-22 09:19 UTC, leezer94 commented on src/hooks/useAuthMethod.js
> +const useAuthMethod = initialValue => {
저도 같은 의견이긴 한데 차라리 contextApi 이용해서 auth관련 부분만 전역으로 관리되어도 괜찮을거 같은데 어떠실까요 ?

2022-12-22 09:20 UTC, leezer94 commented on src/hooks/useInput.js
> +import { useMemo, useState } from 'react';
useMemo 제거후에 push 하여 resolve 하겠습니다~

2022-12-22 09:22 UTC, dev-dong-su commented on src/hooks/useAuthMethod.js
> +const useAuthMethod = initialValue => {
음 UI랑 기능을 최대한 분리하고 싶어서 그냥 나누긴 했는데 contextApi로 전역으로 관리하는게 좋은 생각인것 같아요!

2022-12-22 09:25 UTC, leezer94 commented on src/utils/constants/ErrorMessage.js
> +export default MESSAGE;
constants 폴더는 utils/ 의 하위보다는  src/ 하위에서 관리되는 것이 적합할것 같아 디렉토리 이동 하겠습니다.

2022-12-22 09:33 UTC, dev-dong-su commented on src/hooks/useAuthMethod.js
> +    onChange: setAuthMethod,
일단 setAccountMethod로 이름을 수정했습니다~

2022-12-22 09:33 UTC, dev-dong-su commented on src/hooks/useAuthMethod.js
> +  const [authMethod, setAuthMethod] = useState(initialValue);
AccountMethod라고 이름을 바꿔봤는데 어떤가용??

2022-12-22 09:35 UTC, dev-dong-su commented on src/components/RadioGroup.js
> +      <RadioContext.Provider value={rest}>{children}</RadioContext.Provider>
라디오 그룹을 나중에 재활용 할때 안에 Radio 컴포넌트의 수를 좀더 유연하게 처리하고 싶어서 일단 컨텍스트로 처리를 해보았습니다. 
props drilling이 심하지 않아서 사용하지 않아도 되긴 합니다!

2022-12-22 09:36 UTC, leezer94 commented on src/utils/constants/Validations.js
> +const Validations = {
대문자 변환 완료 하였습니다~

2022-12-22 09:36 UTC, dev-dong-su commented on src/utils/constants/ErrorMessage.js
> +export default MESSAGE;
확인 하였습니다!

2022-12-22 09:40 UTC, dev-dong-su commented on src/hooks/useInput.js
> +  const getPattern = Validations[pattern];
좋은 생각입니다~ 변경 하였습니다!

2022-12-22 09:43 UTC, dev-dong-su commented on src/components/common/Radio.js
> +        type="radio"
오잉 질문을 잘 이해 못했어용..
라디오 버튼은 원래 input으로 구현하지 않나요?

2022-12-22 10:32 UTC, leezer94 commented on src/components/common/Radio.js
> +        type="radio"
제가 이해한것이 맞다면 todo의 completed 상태를 보여주는것을 input radio type 으로 구현하신것 같은데 
UI 적인 측면 말고 semantic 한 측면에서 왜 `input type="radio"` 를 사용하신지를 물어보시는것 같아요.

2022-12-22 11:23 UTC, dev-dong-su commented on src/components/account/Join.js
> +      errorMessage: '비밀번호가 8자 이상인지 확인해 주세요.',
메시지 상수화 완료했습니다~

2022-12-22 11:24 UTC, dev-dong-su commented on src/components/account/Join.js
> +      pattern: 'email',
좋습니다~ 바로 반영하였습니다~

2022-12-22 11:24 UTC, dev-dong-su commented on src/hooks/useLocalStorage.js
> +  return { storedValue, setValue, deleteValue };
바로 반영하였습니다~

2022-12-22 11:25 UTC, dev-dong-su commented on src/hooks/useRequest.js
> +  const loginRequest = (response) => {
더 직관적이고 좋은것 같습니다! handleSignInSuccess, handleSingupSuccess 로 바꾸었습니다~

2022-12-22 11:52 UTC, dev-dong-su commented on src/hooks/useInput.js
> +    event.target.value.match(getPattern) ? setValid(pre => true) : setValid(pre => false);
혹시 `!!`연산자 문서 링크가 있을까용?

2022-12-22 11:55 UTC, dev-dong-su commented on src/hooks/useRequest.js
> +      if (error.response.status === 400) {
음 어떤식으로 객체 구조 분해 할당을 적용하면 좋을지 감이 잘 안잡혀서.. 예시가 있을까용?

2022-12-22 11:59 UTC, dev-dong-su commented on src/components/common/Input.js
> +      {!valid && <ErrorMessage>{errorMessage}</ErrorMessage>}
useInput에 length를 검사하는 코드를 넣어서 해결해보았습니다~!

2022-12-22 11:59 UTC, dev-dong-su commented on src/utils/constants/Validations.js
> +    email: '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$',
뭔가 제 생각에는 include @ 랑 length >= 8 이 방법도 있지만 정규식이 좀더 커버리지가 크다는 생각이 들어서 더 좋은 방법인것 같은데 어떤가용??

2022-12-22 12:30 UTC, Limttugi commented on src/utils/constants/Validations.js
> +    email: '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$',
음... 정규식이 좋다고 생각되는데 과제 조건이 저거네요 ㅜㅜㅜ.... 그래도 정규식이 낫겠죠?

2022-12-22 12:34 UTC, minkyung00 commented on src/router/Router.js
> +  return storedValue === undefined || storedValue === null ? <Navigate to="/" /> : <TmpPpage />;
@dev-dong-su 토큰 값이 없으면 로그인 페이지로 이동하는것만 고려했더니 잘못 생각한 것 같습니다 ㅎㅎ

2022-12-22 12:45 UTC, minkyung00 commented on src/hooks/useInput.js
> +    event.target.value.match(getPattern) ? setValid(pre => true) : setValid(pre => false);
수정했습니다!

2022-12-22 12:56 UTC, minkyung00 commented on src/hooks/useRequest.js
> +  const handleRequest = ({submitFunction, formData, action}) =>
수정했습니다!

2022-12-22 12:56 UTC, minkyung00 commented on src/hooks/useRequest.js
> +      if (error.response.status === 400) {
수정했습니다!

2022-12-22 13:01 UTC, minkyung00 commented on src/components/common/Radio.js
> +        type="radio"
@dev-dong-su  
leezer94님 말처럼 semantic한 측면에서 로그인 / 회원가입을 `input type="radio"`로 구현한 것인지 물어본 것이었습니다!

저는 탭 UI라고 생각했는데 `input type="radio"`로 구현한 다른 이유가 있는지 궁금했습니다!

![image](https://user-images.githubusercontent.com/80238096/209139411-3425f8da-a351-425f-b5c2-aac3a2937be4.png)

2022-12-22 13:19 UTC, minkyung00 commented on src/hooks/useAuthMethod.js
> +const useAuthMethod = initialValue => {
@leezer94 @dev-dong-su 

현재 화면이 회원가입인지, 로그인인지에 관한 상태를 관리하고 있습니다!
이 부분은 Account 페이지에서만 사용하기 때문에 굳이 context를 사용하지 않아도 될 것 같은데요! 

혹시 context로 관리해야하는 이유가 있을까요?

2022-12-22 14:34 UTC, leezer94 commented on src/hooks/useAuthMethod.js
> +const useAuthMethod = initialValue => {
아 전 유저의 로그인 유무를 관리하는 hook 으로 이해를 했었네요 그럼 지역상태로 관리하는게 좋을것 같아요!

2022-12-22 14:40 UTC, leezer94 commented on src/utils/constants/Validations.js
> +    email: '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$',
@Limttugi @dev-dong-su 
당시에 논점이 과제 요구 사항을 충족하는 정도의 커버리지를 맞추냐 아니면 정규식을 이용해서 @dev-dong-su 님 말씀처럼 더 넓은 범위까지 커버 하냐 차이였던것 같아요

후자에서는 정규식을 복붙이 아닌 알고 썻다는 전제가 있어야 될것 같아요

2022-12-22 14:53 UTC, dev-dong-su commented on src/components/common/Radio.js
> +        type="radio"
음 로그인 탭이랑 회원가입 탭의 각자의 상태를 관리 하는것 보다 하나의 상태로 여러 항목을 제어하고 싶어서 해본 고민이였는데 의미에 맞게 적용이 된건지 잘 모르겠네요...ㅎㅎ

2022-12-22 15:36 UTC, leezer94 commented on src/components/RadioGroup.js
> +      <RadioContext.Provider value={rest}>{children}</RadioContext.Provider>
RadioContextProvider 로 전환 하여 resolve 하겠습니다.

2022-12-22 15:36 UTC, leezer94 commented on src/hooks/useAuthMethod.js
> +const useAuthMethod = initialValue => {
지역상태로 전환하여 resolve 하겠습니다.

2022-12-22 15:59 UTC, minkyung00 commented on src/hooks/useAuthMethod.js
> +  const [authMethod, setAuthMethod] = useState(initialValue);
@dev-dong-su 
아! 제가 말했던거는 Method라는 단어가 걸렸던거였어요! Auth는 괜찮은데 Method라는게 왠지 함수를 의미하는 메서드를 말하는거 같아서요! 
저도 네이밍 고민해보겠습니🤔

2022-12-22 16:05 UTC, minkyung00 commented on src/utils/constants/Validations.js
> +    email: '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$',
기존에 저였으면 실제 사용까지 고려해서 정규식을 썼을텐데요! 
화요일 줌 세션에서 과제 요구 이상의 것이 하지말라는 말씀이 마음에 걸리긴 하네요 🤔

2022-12-22 16:07 UTC, minkyung00 approved these changes

2022-12-23 02:18 UTC, minkyung00 commented on src/utils/constants/Validations.js
> +    email: '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$',
과제 방식으로 변경하였습니다!

2022-12-23 02:54 UTC, merged